### PR TITLE
Fix for #82

### PR DESCRIPTION
**Pull request by sero583**
Do your work proper @PikyCZ such small things can cause to shitty errors.

### CODE REVIEW

**Comment by PikyCZ** [comment]
And? .. this plugin is.. you make pull for nothing..

**Comment by sero583** [comment]
@PikyCZ Yes, this plugin is very bad organized but the base idea on itself was well. That disorder and confusion was created by you though. Also I made it atleast be able to start with this pull.

**Comment by PikyCZ** [comment]
Here is original > https://github.com/kniffo80/mob-plugin

**Comment by PikyCZ** [comment]
i know.. this plugin is very bad.. but  basic code is from https://github.com/kniffo80/mob-plugin

**Pull request merged**
